# Pandas

In [23]:
d ={"key1":1,"key2":"Ganesh"}

In [24]:
d

{'key1': 1, 'key2': 'Ganesh'}

In [25]:
d['key2']

'Ganesh'

## Series

In [1]:
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Pandas has explisit sense of index so it is little diffrent than nparray

In [3]:
phone_dict = {'India': 91,
                   'pakistan': 92,
                   'Bangladesh': 880,
                   'africa':770 ,
                   'afganistan': 845}
pd.Series(phone_dict)

India          91
pakistan       92
Bangladesh    880
africa        770
afganistan    845
dtype: int64

very fancy kind of dictionary to series transformation

## DataFrame

In [4]:
population={'India': 1000000000,
                   'pakistan': 48526565,
                   'Bangladesh': 566565665,
                   'africa':155655489565 ,
                   'afganistan': 4555778}
No_Of_phones = {'India': 10050000,
                   'pakistan': 185265,
                   'Bangladesh': 966565,
                   'africa':555655 ,
                   'afganistan': 80000}

In [27]:
pd.DataFrame({'country_code': phone_dict,'population': population,
                       "No_Of_phones":No_Of_phones})

country_code    population  No_Of_phones
Bangladesh           880     566565665        966565
India                 91    1000000000      10050000
afganistan           845       4555778         80000
africa               770  155655489565        555655
pakistan              92      48526565        185265

In [5]:
countries = pd.DataFrame({'country_code': phone_dict,'population': population,
                       "No_Of_phones":No_Of_phones})
countries

country_code    population  No_Of_phones
Bangladesh           880     566565665        966565
India                 91    1000000000      10050000
afganistan           845       4555778         80000
africa               770  155655489565        555655
pakistan              92      48526565        185265

In [6]:
#like serise this data frame also has index
countries.index

Index(['Bangladesh', 'India', 'afganistan', 'africa', 'pakistan'], dtype='object')

In [7]:
countries.columns

Index(['country_code', 'population', 'No_Of_phones'], dtype='object')

In [8]:
countries.country_code

Bangladesh    880
India          91
afganistan    845
africa        770
pakistan       92
Name: country_code, dtype: int64

In [28]:
countries["population"]
countries.to_csv("countries.csv")

## DataFrame as two-dimensional array

In [10]:
countries.values


array([[         880,    566565665,       966565],
       [          91,   1000000000,     10050000],
       [         845,      4555778,        80000],
       [         770, 155655489565,       555655],
       [          92,     48526565,       185265]])

In [11]:
countries.T

Bangladesh       India  afganistan        africa  pakistan
country_code         880          91         845           770        92
population     566565665  1000000000     4555778  155655489565  48526565
No_Of_phones      966565    10050000       80000        555655    185265

In [12]:
countries.values[0]

array([      880, 566565665,    966565])

In [13]:
#iloc index should be numerical
countries.iloc[:3, :2]

country_code  population
Bangladesh           880   566565665
India                 91  1000000000
afganistan           845     4555778

In [14]:
#loc should be index with column and row names
countries.loc[:'pakistan', :'population']


country_code    population
Bangladesh           880     566565665
India                 91    1000000000
afganistan           845       4555778
africa               770  155655489565
pakistan              92      48526565

In [15]:
#hybrid
countries.ix[:3, :'population']


/home/ganesh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


country_code  population
Bangladesh           880   566565665
India                 91  1000000000
afganistan           845     4555778

In [16]:
#Which countrys country_code is bellow  100
countries[countries.country_code<100]

country_code  population  No_Of_phones
India               91  1000000000      10050000
pakistan            92    48526565        185265

### Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame

In [17]:
import numpy as np

In [18]:
np.log(countries)

country_code  population  No_Of_phones
Bangladesh      6.779922   20.155104     13.781504
India           4.510860   20.723266     16.123083
afganistan      6.739337   15.331907     11.289782
africa          6.646391   25.770911     13.227903
pakistan        4.521789   17.697622     12.129543

# Handling Missing Data

None and nan

In [19]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [20]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Why the hell error is?**

In [21]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2

array([ 1., nan,  3.,  4.])

In [22]:
vals2.sum()

nan

In [44]:
1 + np.nan

nan

In [49]:
vals2.sum()

nan

In [50]:
# some jugad that ignores missing value
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [54]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

* isnull(): Generate a boolean mask indicating missing values
* notnull(): Opposite of isnull()
* dropna(): Return a filtered version of the data
* fillna(): Return a copy of the data with missing values filled or imputed


In [56]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [57]:
data.dropna()

0        1
2    hello
dtype: object

In [58]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [59]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [60]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [61]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

## How to load dataset from csv file

In [30]:
births=pd.read_csv("PythonDataScienceHandbook-master/notebooks/data/births.csv")

* count number of NaN values in above data
* remove couln containig NaN value
* Find type of gender column from above data
* in which years birth rate is highest?

In [32]:
np.sum(births.isnull())

year        0
month       0
day       480
gender      0
births      0
dtype: int64